#!/usr/bin/env bash
set -euo pipefail

# ===========================================
# SnipSay - One-Command Setup
# ===========================================

echo ""
echo "=============================================="
echo "  SnipSay - Setup"
echo "=============================================="
echo ""

# Colors (macOS compatible)
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# --- Check for Homebrew ---
if ! command -v brew &>/dev/null; then
    echo -e "${RED}Error: Homebrew not found.${NC}"
    echo "Install it first: https://brew.sh"
    exit 1
fi
echo -e "${GREEN}✓${NC} Homebrew found"

# --- Check for Python 3 ---
if ! command -v python3 &>/dev/null; then
    echo -e "${RED}Error: Python 3 not found.${NC}"
    echo "Install it with: brew install python"
    exit 1
fi
echo -e "${GREEN}✓${NC} Python 3: $(python3 --version | cut -d' ' -f2)"

# --- Install portaudio ---
if ! brew list portaudio &>/dev/null 2>&1; then
    echo "Installing portaudio..."
    brew install portaudio
fi
echo -e "${GREEN}✓${NC} portaudio"

# --- Install ffmpeg ---
if ! command -v ffmpeg &>/dev/null; then
    echo "Installing ffmpeg..."
    brew install ffmpeg
fi
echo -e "${GREEN}✓${NC} ffmpeg"

# --- Create virtual environment ---
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
VENV_DIR="$SCRIPT_DIR/venv"

if [ ! -d "$VENV_DIR" ]; then
    echo "Creating virtual environment..."
    python3 -m venv "$VENV_DIR"
fi
echo -e "${GREEN}✓${NC} Virtual environment ready"

# Activate venv
source "$VENV_DIR/bin/activate"

# --- Install Python packages ---
echo "Installing Python packages (pyaudio, faster-whisper)..."
pip install --upgrade pip -q
pip install pyaudio faster-whisper -q
echo -e "${GREEN}✓${NC} Python packages installed"

# --- Check for Hammerspoon ---
if [ ! -d "/Applications/Hammerspoon.app" ]; then
    echo ""
    echo -e "${YELLOW}Hammerspoon not found.${NC}"
    echo "Install it to enable global hotkeys:"
    echo "  brew install --cask hammerspoon"
    echo ""
    echo "After installing, run:"
    echo "  open -a Hammerspoon"
    echo ""
else
    echo -e "${GREEN}✓${NC} Hammerspoon installed"
fi

# --- Install Hammerspoon config ---
HS_DIR="$HOME/.hammerspoon"
mkdir -p "$HS_DIR"
INIT_LUA="$HS_DIR/init.lua"
MARKER="-- SNIPSAY_CONFIG"
MARKER_END="-- END_SNIPSAY_CONFIG"

# Remove old config if present
if [ -f "$INIT_LUA" ]; then
    if grep -q "$MARKER" "$INIT_LUA"; then
        sed -i '' "/$MARKER/,/$MARKER_END/d" "$INIT_LUA"
        echo "Updated existing Hammerspoon config"
    fi
fi

# Append our config
cat >> "$INIT_LUA" <<EOF

$MARKER
-- SnipSay Configuration
-- Auto-generated by setup.sh
dofile("$SCRIPT_DIR/init.lua")
$MARKER_END
EOF

echo -e "${GREEN}✓${NC} Hammerspoon configured"

# --- Install user config file ---
mkdir -p "$HOME/snipsay"
cp "$SCRIPT_DIR/config.lua" "$HOME/snipsay/config.lua"
echo -e "${GREEN}✓${NC} Config installed at ~/snipsay/config.lua"

# --- Pre-download model ---
echo ""
echo "Pre-downloading Whisper 'base' model..."
"$VENV_DIR/bin/python3" -c "
from faster_whisper import WhisperModel
print('Downloading...')
model = WhisperModel('base', device='cpu', compute_type='float32')
print('Model ready!')
" 2>/dev/null || echo -e "${YELLOW}Model will download on first use${NC}"

echo ""
echo "=============================================="
echo -e "${GREEN}  Setup Complete!${NC}"
echo "=============================================="
echo ""
echo "Next steps:"
echo ""
echo "  1. Start SnipSay:"
echo "     cd $SCRIPT_DIR"
echo "     ./start.sh"
echo ""
echo "  2. If Hammerspoon is installed, reload config:"
echo "     Click the 📊 icon in menu bar → Reload Config"
echo ""
echo "  3. Press ${YELLOW}Ctrl+Shift+Space${NC} to:"
echo "     - Start recording"
echo "     - Stop recording & transcribe"
echo ""
echo "  4. Your transcribed text is copied to clipboard!"
echo ""
echo "=============================================="
echo ""
echo "To change the hotkey, edit: ~/snipsay/config.lua"
echo "See README.md for customization options."
echo ""
